### ISSUE TITLE
accept index.html as base template

### ISSUE THREAD

**Issue by gasolin** [mozilla-neutrino/neutrino-preset-web#6]
its strange when a `web` preset doesn't support `index.html` but only `index.ejs`

`index.html` also looks more familiar to new comers when there's a tutorial.

**Comment by eliperelman** [comment]
This is because html-webpack-plugin by default uses EJS templates to generate HTML files. They are EJS files because, while not necessarily in use by neutrino, it's possible to pass metadata to the template through config.

**Comment by gasolin** [comment]
update: its `template.ejs` instead of index.html

I fully understand the context of inheritance from `html-webpack-plugin`. 

At least with `html-webpack-plugin` its possible to use `index.html` as the template
https://www.jonathan-petitcolas.com/2016/01/23/webpack-html-plugin-in-a-nutshell.html

if you don't mind I can make a patch to accept `index.html` as the template
1. default `template.ejs` (current)
2. `template.ejs`  in project (current)
3. `index.html`  in project (new)

How do you think?
