### ISSUE TITLE
exclude js and eslint processing in `src/static` folder

### ISSUE THREAD

**Issue by gasolin** [mozilla-neutrino/neutrino-preset-web#7]
It's always happen when dev need to put some vendor libraries in code base.

**Comment by eliperelman** [comment]
In order to do this, we would need to standardize what the default static directory is, e.g. `src/static`. Contenders could be `static`, `public`, or `assets`. I believe there would also need to be other config changes needed to support this.

**Comment by gasolin** [comment]
I saw some configuration use `static` as non processed folder, and `assets` as recommend processable folder.. (Though I forget the source)

**Comment by eliperelman** [comment]
This issue was moved to mozilla-neutrino/neutrino-dev#4
